// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/luis/Desktop/appBiscoito/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/luis/Desktop/appBiscoito/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('c:/Users/luis/Desktop/appBiscoito/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('appBiscoito', appParameters);
});